In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.subplots as sp
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [7]:
pwd

'/content'

In [8]:
df = pd.read_csv(r'/content/sample_data/diamonds.csv')

In [9]:
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [10]:
df.drop_duplicates()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [11]:
df.drop(['Unnamed: 0'],axis=1,inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [13]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [14]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
numerical_columns = ['carat', 'depth', 'table', 'price', 'x', 'y', 'z']

num_rows = (len(numerical_columns) // 2) + (len(numerical_columns) % 2)
num_cols = 2

fig = sp.make_subplots(rows=num_rows, cols=num_cols,
                       subplot_titles=numerical_columns,
                       vertical_spacing=0.1)
for i, column in enumerate(numerical_columns):
    row = (i // num_cols) + 1
    col = (i % num_cols) + 1
    trace = go.Histogram(x=df[column], nbinsx=30)
    fig.add_trace(trace, row=row, col=col)

fig.update_layout(height=num_rows * 500, width=num_cols * 400,
                  title_text='Histogram  of Numerical columns',showlegend=False)
fig.update_yaxes(title_text='Frequency')
fig.update_xaxes(title_text='Value')

fig.show()

. All numerical columns are not normally distributed

In [ ]:
fig = make_subplots(rows=1 ,cols =3,subplot_titles=['cut','color','clarity'])

fig.add_trace(go.Bar(x=df['cut'].value_counts().index,y=df['cut'].value_counts().values),row=1,col=1)
fig.add_trace(go.Bar(x=df['color'].value_counts().index,y=df['color'].value_counts().values),row=1,col=2)
fig.add_trace(go.Bar(x=df['clarity'].value_counts().index,y=df['clarity'].value_counts().values),row=1,col=3)
fig.update_layout({'title':{'text':'univariant on numerical columns',
                                   'x':0.5,'y':0.9,
                                   'font_size':26,
                                   'font_color':'black'}},showlegend=False)
fig.show()

.In these categorical columns ideal cut,color G, clarity SI1 are maximum

In [ ]:
numerical_columns = ['carat', 'depth', 'table', 'x', 'y', 'z']

num_rows = (len(numerical_columns) // 2) + (len(numerical_columns) % 2)
num_cols = 3

fig = sp.make_subplots(rows=num_rows, cols=num_cols,
                       subplot_titles=numerical_columns,
                       vertical_spacing=0.1)
for i, column in enumerate(numerical_columns):
    row = (i // num_cols) + 1
    col = (i % num_cols) + 1
    trace = go.Scatter(x=df[column],y=df['price'],mode='markers')
    fig.add_trace(trace, row=row, col=col)

fig.update_layout(height=num_rows * 500, width=num_cols * 400,
                  title_text='price vs numerical columns')
fig.update_yaxes(title_text='price')
fig.update_xaxes(title_text=column)


fig.show()

. In all these price vs numerical columns price is increasing with carat and variable x

In [ ]:
box_fig = px.box(df, x='cut', y='price',
                 title='Box Plot of Price by Cut',
                 labels={'cut': 'Cut Quality', 'price': 'Price'})
box_fig.show()

In [ ]:

numerical_columns = ['carat', 'depth', 'table', 'price', 'x', 'y', 'z']
numerical_data = df[numerical_columns]
corr_matrix = numerical_data.corr()


heatmap_fig = go.Figure(data=go.Heatmap(
                   z=corr_matrix.values,
                   x=corr_matrix.columns,
                   y=corr_matrix.columns,
                   colorscale='gray',
                   colorbar=dict(title="Correlation"),
                   zmin=-1, zmax=1))

heatmap_fig.update_layout(title="Correlation Heatmap",
                          xaxis=dict(title="Features"),
                          yaxis=dict(title="Features"))
heatmap_fig.show()

.There is maximum  correlation with price with carat and variable x

In [ ]:
fig = px.scatter_3d(df, x='carat', y='depth', z='price', color='price',
                    title='3D Scatter Plot of Price')
fig.show()

.From this plot price is increasing with carat but not with depth

**Observations**

####.There is maximum correalation  price vs carat and with price with column and next with cut
####. There are outliers in every numerical column
#### . Price with increasing with increasing carats of diamond
#### . Price is not affected with increasing depth
####. Price is  also increases with clarity and column